### ISSUE TITLE
Update examples to use Tuple.pair instead of (,)

### ISSUE THREAD

**Issue by bowbahdoe** [zwilias/elm-reorderable#1]
There was a conversation in the elm slack in which someone was confused by the usage of the `(,)` in the example in the readme. This should be updated to Elm 0.19 to avoid future confusion.

![image](https://user-images.githubusercontent.com/5004262/63742508-0f932900-c867-11e9-9974-c3893af68294.png)

**Comment by TwistingTwists** [comment]
I have already created a pull request for the same. 

https://github.com/zwilias/elm-reorderable/pull/2/commits/221e81e0a1dfa204caa97934cd1ec218f2783ee5

**Comment by zwilias** [comment]
Thanks so much! (Closed by #2 )
